dataset_path: glab-caltech/FGVQA
task: "fgvqa_inquire"
test_split: test
process_docs: !function utils.inquire_process_docs
output_type: generate_until
doc_to_visual: !function utils.inquire_doc_to_visual
doc_to_text: !function utils.inquire_doc_to_text
doc_to_target: !function utils.inquire_doc_to_target
process_results: !function utils.inquire_process_results
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false
metric_list:
  - metric: pairwise_total
    aggregation: !function utils.inquire_pairwise_aggregate
    higher_is_better: true
  - metric: multiple_choice_total
    aggregation: !function utils.inquire_multiple_choice_aggregate
    higher_is_better: true
  - metric: overall_total
    aggregation: !function utils.inquire_overall_aggregate
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "You MUST include an explanation AND use the answer tags <answer></answer>."
metadata:
  - version: 0.0
  - source: "glab-caltech/FGVQA (fgvqa_inquire subset)"
  - pairwise_total: 1000
  - pairwise_yes: 500
  - pairwise_no: 500
  - multiple_choice_total: 1000
