dataset_path: vikhyatk/CountBenchQA
task: "countbenchqa"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.countbenchqa_doc_to_visual
doc_to_text: !function utils.countbenchqa_doc_to_text
doc_to_target: !function utils.countbenchqa_doc_to_target

generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: false
    ignore_punctuation: false
    ignore_numbers: false

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer with an exact integer"

metadata:
  - version: 0.0
