# Official STARE paper use this configuration
dataset_name: null
test_split: test
task: "omnispatial_test"
include: _default_template_yaml
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Answer with just the letter inside <answer> tags."
